# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allowfun <- function(lu, hist, codes, changedir, rules) {
    .Call('_lulcc_allowfun', PACKAGE = 'lulcc', lu, hist, codes, changedir, rules)
}

autoconvert <- function(lu, mask, prob, codes) {
    .Call('_lulcc_autoconvert', PACKAGE = 'lulcc', lu, mask, prob, codes)
}

inC <- function(x, table) {
    .Call('_lulcc_inC', PACKAGE = 'lulcc', x, table)
}

orderC <- function(x, decreasing) {
    .Call('_lulcc_orderC', PACKAGE = 'lulcc', x, decreasing)
}

ordered <- function(lu0, tprob, dmd, alloc_order, categories, stochastic, maxiter) {
    .Call('_lulcc_ordered', PACKAGE = 'lulcc', lu0, tprob, dmd, alloc_order, categories, stochastic, maxiter)
}

updatehist <- function(lu0, lu1, hist) {
    .Call('_lulcc_updatehist', PACKAGE = 'lulcc', lu0, lu1, hist)
}

